# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' This is a test function for Rcpp
#' @export
rcpp_hello_world <- function() {
    .Call('yapomif_rcpp_hello_world', PACKAGE = 'yapomif')
}

